### PR TITLE
Noteclass

### PR DESCRIPTION
**Pull request by snspzv**

### CODE REVIEW

**Review by magneticflux- — CHANGES_REQUESTED** [review]
- Notes `A` and `B` are missing, will we support them?
- It might be useful to statically declare some common notes so we don't have to create and destroy objects frequently.
- Exponents can be static numbers like `#define ROOT_1 = 1.059463` and then `#define ROOT_2 = ROOT_1 * ROOT_1` and they can be put in a lookup table and wrapped in a utility function like `getNRoot(2)`.

**Review by magneticflux- — DISMISSED** [review]

**Comment by snspzv** [comment]
I just forgot A and B because the octaves start with C, so I’ll add those. 

Ok, I’ll create common notes for the 4th octave since that’s where I’m doing the preset songs. Do you mean at compile time or just have them in main at run time?

Ok I’ll change that.

**Comment by magneticflux-** [comment]
No problem!

Okay, sounds good. At compile time, just make them static somewhere I guess.

👍

Remember to rebase or let me know if you want me to do it!

**Comment by snspzv** [comment]
I added the lookup table and A and B. Do you mean something like I have above main for the common notes?

**Comment by snspzv** [comment]
Also does rebase just mean resolve conflicts?

**Comment by magneticflux-** [comment]
Yeah, I think that's fine! I'd like to make some changes myself, and I can merge/rebase at the same time.

**Comment by magneticflux-** [comment]
@snspzv I did some optimization/refactoring to the powers-of-two function in 40b8cd97dd5805b8e3719c3580366f8400d213db.

**Review by magneticflux- — DISMISSED** [review]
I'm happy with how it is, except more common notes should be declared statically like `C4` is already.

**Review by magneticflux- — APPROVED** [review]

**Pull request merged**
